### ISSUE TITLE
Unavailable in red-node palette and npm

### ISSUE THREAD

**Issue by aroslanov** [bartbutenaers/node-red-contrib-onvif-nodes#1]
Any chance to have it back?

**Comment by bartbutenaers** [comment]
Hi Timur,

This node has never been available in npm yet.  I have been working meanwhile on other Node-RED contributions, so this one is still experimental.

I have planned to continue the developments this winter, but I need to discuss the setup on the Node-RED forum before I publish the first version on NPM. 
If you want to experiment with this meanwhile, be my guest!  You can install it directly from Github:
```
npm install bartbutenaers/node-red-contrib-onvif
```
P.S. One of the main issues is that the underlying NodeJs Onvif library seems not to be maintained anymore ...

Kind regards,
Bart

**Comment by bartbutenaers** [comment]
Hi Timur (@aroslanov ),

I have published a beta version on NPM, which is currently being tested by a series of members on the Node-RED community (see [discussion](https://discourse.nodered.org/t/onvif-camera-control/6888/44?u=bartbutenaers)).  As soon as that discussion is finished, I will publish a final version on NPM.

Therefore I'm going to close this issue now.
Bart
