### ISSUE TITLE
Cant see nodes on my web interface

### ISSUE THREAD

**Issue by greyser83** [bartbutenaers/node-red-contrib-onvif-nodes#11]
![image](https://user-images.githubusercontent.com/49680277/92462293-f986ab00-f1d2-11ea-8fd8-7a29349e8e9f.png)
Hello, Bart! Just installed your package with command
npm install node-red-contrib-onvif-nodes , but there is no node on my node red web interface.
Command npm install node-red-contrib-onvif-nodes@0.0.1-beta.7 was unable to install package due to multiple errors.
![image](https://user-images.githubusercontent.com/49680277/92462665-7023a880-f1d3-11ea-9a41-b86872aee322.png)

**Comment by bartbutenaers** [comment]
Hi @greyser83 ,
These nodes are already for a long time in beta phase (as you can read [here](https://discourse.nodered.org/t/announce-node-red-contrib-onvif-nodes-beta-7-event-streaming/23437)). 
Had no time yet to create a final release for npm.
Which means you have to install them via the [command ](https://github.com/bartbutenaers/node-red-contrib-onvif-nodes#install) on my readme page...
Bart

**Comment by greyser83** [comment]
Bart, but using this command causes errors as i noticed earlier08.09.2020, 14:14, "bartbutenaers" <notifications@github.com>:
Hi @greyser83 ,
These nodes are already for a long time in beta phase (as you can read here).
Had no time yet to create a final release for npm.
Which means you have to install them via the command  on my readme page...
Bart

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- С уважением,Сергей Костромин

**Comment by bartbutenaers** [comment]
Damn, I misread your command.  Sorry.
Don't know why it fails.  Otherwise try to install it directly from Github:
```
npm install bartbutenaers/node-red-contrib-onvif-nodes
```
Hopefully that works...

**Comment by greyser83** [comment]
Sorry, butnpm install bartbutenaers/node-red-contrib-onvif-nodesalso causes errors08.09.2020, 15:20, "bartbutenaers" <notifications@github.com>:
Damn, I misread your command.  Sorry.
Don't know why it fails.  Otherwise try to install it directly from Github:
npm install bartbutenaers/node-red-contrib-onvif-nodes

Hopefully that works...

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- С уважением,Сергей Костромин

**Comment by bartbutenaers** [comment]
Hi @greyser83 ,
Could you please post this question on the Node-RED forum (discourse.nodered.org), with your screenshots and mention my name there.  There are people in the community with lots of npm experience, who might be able to solve your problem.
Thanks!

**Comment by bartbutenaers** [comment]
Hi @greyser83,
Have you been able meanwhile to solve the installation problem?  Because I see now in your screenshot above that there was a problem installing ...agsh/onvif.git dependency.   Last night I have merged a [pull-request](https://github.com/bartbutenaers/node-red-contrib-onvif-nodes/pull/15) about this, so maybe it is solved when you could try it again...

**Comment by greyser83** [comment]
Yes! first, check  if git is already installed 20.10.2020, 13:16, "bartbutenaers" <notifications@github.com>: Hi @greyser83,Have you been able meanwhile to solve the installation problem? Because I see now in your screenshot above that there was a problem installing ...agsh/onvif.git dependency. Last night I have merged a pull-request about this, so maybe it is solved when you could try it again...—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.  -- С уважением,Сергей Костромин

**Comment by bartbutenaers** [comment]
Thanks for the feedback.  I have added the 'git' requirement to the readme page, to avoid that other users have the same issue as you...
