### ISSUE TITLE
Events motion detection multiple camera's

### ISSUE THREAD

**Issue by prutspapa** [bartbutenaers/node-red-contrib-onvif-nodes#13]
Bart, I believe I might have found an issue with the event feedback.
I have 2 camera's, 1 on the frontdoor, 1 on the driveway, both setup with motion detection.
I notice that when one of the camera's gets a motion alert event, also the motion alert event of the second camera is triggered.
I put a counter on the number of messages I get, and these are always the same.  I suspect there is no differentiation from which camera the event message comes from.
I can do more testing if you like.
Kind regards,
Dirk

**Comment by bartbutenaers** [comment]
Hi Dirk,
Thanks for reporting this issue!
This is something that I should test, because I cannot detect a problem by simply looking at the code.  
To be continued...
Bart

**Comment by bartbutenaers** [comment]
Unfortunately I cannot get this reproduced.
+ Do you have this also after a system restart, or only after a deploy?
+ So you have two config nodes, one for each camera?
+ Is there anything else that you have noticed, which could help me in finding this issue?

**Comment by prutspapa** [comment]
Bart, strange thing, I was trying to find out how it worked, I appears like, while I reinstalled your module, the onvif module itself was not reinstalled,  So I manually installed the latest version, not it seems to be working.  
Have not tried it on a fresh system.
So problem solved

**Comment by prutspapa** [comment]
thankx for the effort
