### ISSUE TITLE
Not showing in Pallette:Totally new to Node Red-

### ISSUE THREAD

**Issue by o0Speaker0o** [bartbutenaers/node-red-contrib-onvif-nodes#16]
Hi, just discovered this. I'm trying to use onvif to read alerts.
I installed but cant see this in the pallette. 
here is my install text

mike@ucdc-server:~/.node-red$ npm install bartbutenaers/node-red-contrib-onvif-nodes
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/i                      ssues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
+ node-red-contrib-onvif-nodes@0.0.1-beta.9
updated 1 package and audited 127 packages in 24.133s

1 package is looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
mike@ucdc-server:~/.node-red$ npm install node-red-contrib-onvif-nodes@0.0.1-beta.3
+ node-red-contrib-onvif-nodes@0.0.1-beta.3
removed 45 packages, updated 2 packages and audited 82 packages in 5.017s

1 package is looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by bartbutenaers** [comment]
Hi @o0Speaker0o,
Did you refresh your browser window, where the flow editor is running?  
Bart

**Comment by o0Speaker0o** [comment]
Yes, I even restarted the node red service  on the server.
...<sigh> 
Just checked to send a screenshot.... and there it is :-O
call me embarrassed, close the ticket, and accept my thanks
A coffee for the wife will be coming. :-)

**Comment by bartbutenaers** [comment]
No problem at all.
When I started with Node-RED I forgot to refresh all the time :-)
