### ISSUE TITLE
Onvif-Device not with different Port

### ISSUE THREAD

**Issue by Christchoper** [bartbutenaers/node-red-contrib-onvif-nodes#19]
It is not possible to specify a port in the Onvif config node. My camera listens to port 8000. I tried with IPadress:8000 but no connection is possible. 
Error Msg:
node: Kamera
msg : error
"Error: getaddrinfo ENOTFOUND 192.168.10.245:8000"

**Comment by bartbutenaers** [comment]
Hi @Christchoper,
Have you seen this on the [readme ](https://github.com/bartbutenaers/node-red-contrib-onvif-nodes#install) page:

![image](https://user-images.githubusercontent.com/14224149/102504754-828a6980-4081-11eb-8c00-0932c8f7886e.png)

I assume you use the old version from NPM ?
Bart

**Comment by Christchoper** [comment]
Hi Bart,
Thank you for your quick reply. Unfortunately I am not able to install git on my RaspberryMatic (CCU3). Can you maybe help me there. Best regards, Chris

**Comment by bartbutenaers** [comment]
I have installed the latest beta version on npm:

![image](https://user-images.githubusercontent.com/14224149/102549418-59d39580-40bc-11eb-97cd-2261c6e10357.png)

So you should be able to install it like this:
```
npm install node-red-contrib-onvif-nodes
```

**Comment by Christchoper** [comment]
I have now uninstalled beta4 and tried to install the new version. Unfortunately I get an error:

_root@homematic-raspi:~# cd /usr/local/addons/redmatic/var
root@homematic-raspi:/usr/local/addons/redmatic/var# npm install node-red-contri
b-onvif-nodes
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/agsh/onvif.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm-cache/_logs/2020-12-18T11_17_07_788Z-debug.log_

**Comment by bartbutenaers** [comment]
The "latest" version on npm is version 0.0.1-beta.12, so not sure why you get that old version.
I think you can install the latest version like this:
```
npm install node-red-contrib-onvif-nodes@0.0.1-beta.12
```

**Comment by Christchoper** [comment]
Thank you very much for the advice. Unfortunately, that does not work either. I tried it on my CCu3 and on my test environment. I have sent you the error log in the attachment. Can you find anything there that points to the problem? Thanks for your help.


[2020-12-18T12_34_15_580Z-debug.log](https://github.com/bartbutenaers/node-red-contrib-onvif-nodes/files/5715665/2020-12-18T12_34_15_580Z-debug.log)

**Comment by bartbutenaers** [comment]
For me this works fine:

![image](https://user-images.githubusercontent.com/14224149/102659897-71715380-417a-11eb-8e36-661b0b8a6a92.png)

I have run out of creativity...
If I were you, it would ask your question on the Node-RED [forum](discourse.nodered.org).  Since there is a lot of npm knowledge available in the community...

**Comment by bartbutenaers** [comment]
This problem was solved via Discourse
