### ISSUE TITLE
Invalid handling xAddress with port

### ISSUE THREAD

**Issue by av1024** [bartbutenaers/node-red-contrib-onvif-nodes#2]
Nothing worked if  I pass xAddress as IP:Port.
After digging a while I found it:
 - onvif.Cam `options` uses `hostname` and `port` for configuration, but in config node there is simple assign `options.hostname = this.xaddr`

- Solution 1 (as I did on local copy): add extra config parameter 'xport' and assign to `options.port`
- Solution 2: parse passed xaddress string for ':<number>' and extract port number from it

**Comment by av1024** [comment]
Oops!
Looks like all done in git, but not on npm.
Close.

**Comment by bartbutenaers** [comment]
Hi Alexander,
Thanks for the analysis!  

Unfortunately I have no time for Node-RED this week, but do you mean the code on Github is working, and the one on NPM not?  Thought I had published all my changes before I left...

P.S. If you have other feedback, please let me know here or in the discussion on the forum (see link in readme file).
Bart

**Comment by av1024** [comment]
Hi!
I don't tested current git code, but just looked at onvif_config.html here and found the 'port' option already added. So only npm repository is unsync with git. 

No more feedback for a week or more. Unfortunately my cheap China's PTZ camera looks so buggy and I temporarily stop trying to make it work :( Next time it will be PTZ preset support digging
