### ISSUE TITLE
error install raspberry pi

### ISSUE THREAD

**Issue by lexrosenot** [bartbutenaers/node-red-contrib-onvif-nodes#23]
Hi, 

when i try install the package i get this error:

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/bartbutenaers/node-red-contrib-onvif-nodes.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-30T01_46_04_688Z-debug.log

[2021-05-30T01_46_04_688Z-debug.log](https://github.com/bartbutenaers/node-red-contrib-onvif-nodes/files/6566311/2021-05-30T01_46_04_688Z-debug.log)

**Comment by lexrosenot** [comment]
i have not idea why, could u help me? or tell me if the project is down

**Comment by bartbutenaers** [comment]
Hey @lexrosenot,

I assume you have installed this node directly from my Github repository using the command on my readme page?  That would be good, because the version on NPM is obsolete.
Do you have Git installed?  It seems to me that he cannot find Git, which is required by the npm command to install the node from this Github repository...

Bart

**Comment by lexrosenot** [comment]
hi bart,
Thanks for your help. You were right. I didn't have "git" installed.

Additionally, I tell you that I could test the nodes with my GADNIC P2P00009 ip camera. All nodes worked fine.

on the other hand, try to stream rtsp through FFMPEG, as explained here (https://discourse.nodered.org/t/how-to-display-cctv-camera-in-dashboard-rtsp/5860/47 ? u = bartbutenaers) but the image has a lot of delay. It is even more performant for me to use the onvif media node with the getSnapshot option and a refresh every 10 seconds. 

Do you think it could be some configuration of the ffmpeg that generates so much freeze in the image?

command: ffmpeg -f rtsp -i "rtsp: //192.168.100.57: 554 / user = admin_password = XXXXXX_channel = 0_stream = 0.sdp?real_stream" -f image2pipe pipe: 1


I thank you again for your help.

**Comment by bartbutenaers** [comment]
Hey @lexrosenot,
You are welcome!
Yes that was only an experiment with rtsp via ffmpeg.  But meanwhile we have a video magician in our Node-RED community (Kevin Godell).  Search for his name and rtsp on Discourse, and you will see that he has create a bunch of custom nodes for video streaming (e.g. [here](https://discourse.nodered.org/t/beta-testing-nodes-for-live-streaming-mp4/33743)), which are WAY better.
Bart

**Comment by lexrosenot** [comment]
thanks a lot !! @bartbutenaers
