### ISSUE TITLE
Action start (stop) is not supported

### ISSUE THREAD

**Issue by ghost** [bartbutenaers/node-red-contrib-onvif-nodes#24]
Hi, I need your help ....
For my Reolink from RLC-410 I used your node without problem.
Two days ago I bought a Reolink RLC-510WA and I have a problem with motion detection.
The instruction "Set - msg.action - start (and stop)" in node red return this error "Action start (stop) is not supported".
So the cam is CONNECTED but not LISTENING.
Can you help me to fix this error?

**Comment by bartbutenaers** [comment]
Hi @RitaSghe,

When you talk about motion detection, then I "assume" you use the event node??
If so you can find explanation and an example flow in the [event-node](https://github.com/bartbutenaers/node-red-contrib-onvif-nodes#event-node) section on my readme page.

You can send "start" or "stop", but not "start (stop)"...

Bart

**Comment by ghost** [comment]
Hi,
yes, I use the event node and I send "start" or "stop", of course :)
I've already read the example in your readme page and with RLC-410 the event node work fine, rather with RLC-510wa I have the error ....
msg.action=start don't work and my cam is not in LISTENING mode ...

**Comment by bartbutenaers** [comment]
Ah ok, I had interpreted you "_Action start (stop) is not supported_" a bit incorrectly ;-)
Can export this part of your flow (both the config node and the node that sends the msg.action input message), and share it here?

**Comment by ghost** [comment]
I just used your example ....

![img01](https://user-images.githubusercontent.com/81916825/126277874-8ebbf91d-08bc-4126-9787-84ddb41b4930.png)

The config node ...

![img02](https://user-images.githubusercontent.com/81916825/126277935-29c12358-6645-4d68-a0a5-090fd11d2a2a.png)

When I start listening nothing happens and this is the error ...

![img032](https://user-images.githubusercontent.com/81916825/126279958-ae035ac6-aa1d-4612-bad7-bbbf01dd7ad3.png)

The cam is CONNECTED but not LISTENING ...

Tell me if you need more information ...

**Comment by bartbutenaers** [comment]
I have been testing this over and over again, and I couldn't understand how this issue could arrise. 
Because that error (normally) can never occur in this node.

> I just used your example ....

Are you sure about that, or have you replaced the Onvif-Event node by an Onvif-Device node?
Because the icon in my example flow looks very different:

![image](https://user-images.githubusercontent.com/14224149/126388735-e6e3b51d-7bb4-48e0-91ba-b2a894cb8b22.png)

Unless I have somewhere posted an incorrect flow (which I cannot find), I assume that is the problem.
When you want to listen to events, you need to use the Onvif-Events node ...

**Comment by ghost** [comment]
Yes, you're right ....
I have seen the node "onvif device" and I thought needed for the configuration of the cam and then I continued with this node.
Thank you very much, I'm so sorry for your trouble and yes, I'm an idiot ......

The only thing I noticed is the long time from when I press "Start listening" to when the node events become "listening" (15/30 sec.); with the old cam this step was immediate (and the same time it's necessary to Stop listening) .... but this is not a problem of your node. Today I test the motion alert ...

Excuse me again, have a nice day.

**Comment by bartbutenaers** [comment]
Hi

**Comment by bartbutenaers** [comment]
Hi @RitaSghe,
I'm glad it finally works!  
Yes I expect the waiting time to be an issue with the new sotware of your new camera.  Might be worth to contact Reolink about that...
Bart
