### ISSUE TITLE
Tapo c200 camera

### ISSUE THREAD

**Issue by fmarzocca** [bartbutenaers/node-red-contrib-onvif-nodes#29]
Hi,

I am using a Tapo Tp-link C200 camera (Onvif). How can I enable/disable Privacy Mode with your node?
Thanks

**Comment by bartbutenaers** [comment]
Hello Fabio (@fmarzocca),

Sorry for the delay.  I had overlooked your question ...

When looking at that [privacy mode](https://www.tp-link.com/ae/support/faq/2791/) feature, it seems to me that it is a typical Tapo feature?   I see that some other camera's implement it by physical movements: e.g. rotate the camera lens, so it cannot record any video anymore. 

I don't think that this is an Onvif feature, but I might be mistaken...  Have you seen anything about this in an Onvif related article perhaps?

But you might be able to accomplish it by using the ***http-request node***, to send a http request to your camera.  There is e.g. a Python library that has implemented a [setPrivacyMode](https://github.com/JurajNyiri/pytapo/blob/87dbd0cbf2285b51051a42099120af72bc0563c1/pytapo/__init__.py#L244) function, which also sends a http request...  And Zoneminder does it the same way in their [sleep](https://raw.githubusercontent.com/oparm/zoneminder-tapo-c200/main/TapoC200.pm) function.

Bart

**Comment by fmarzocca** [comment]
Hi Bart,

thank you for your answer. I don't know much about Tapo's "privacy mode"
feature. I have asked to tp-link support, but they are just answering "use
the app"!
I will have a look at that python library!

Best

Fabio

**Comment by fmarzocca** [comment]
Hi Bart,

I managed to let it working with the pytapo library!
Thank you very much

Fabio

**Comment by bartbutenaers** [comment]
Hey Fabio,
You are welcome!
You could also try to figure out which http requests are being send by that python library.  E.g. by enabling the logs of the http request (e.g. [here](https://bhoey.com/blog/better-debug-logging-for-the-python-requests-library/).  Then you can use a simple http-request node to send the same requests.  That way you have a very simple flow...
Kind regards,
Bart
